name: ml4t_new
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=1.26.*
  - pandas=2.2.*
  - scipy>=1.10
  - matplotlib>=3.7
  - seaborn>=0.13
  - scikit-learn=1.5.*
  - yfinance
  - joblib>=1.2
  - pytest>=7.4
  - pip
  - pip:
      - pytest-json>=0.4